Lor11212/stateless prt wrapper
Esri/puma pull request #41
Opened 2022-02-23 10:14 UTC by lor11212

JIRA: https://zrh-web.esri.com/jira/browse/CE-9592

This PR aims at refactoring the `ModelGenerator` and `RhinoPRTAPI` to make them stateless. This is still a work in progress.

### Implementation

- Removed class variables of `ModelGenerator` and `RhinoPRTAPI` that are used for the generation.
- Removed API functions that were setting rule attribute values to `ModelGenerator`. Instead, attribute values are now encoded into a big map and passed when calling `Generate`.
- Refactored API function `Generate` to take all arguments needed for the generation.
- Refactored API function `Generate` to return meshes, reports and materials in one container object.

**Remaining work:**

- Make the rule attribute extraction stateless.
- Make the default value evaluation stateless as well.
- Add CGA prints and errors to the returned elements of generate.
- Refactor how the flag `doGenerateMaterial` is passed. Add it as an argument of `Generate`.

2022-04-05 15:01 UTC, mistafunk requested changes
Did is a first review pass. I've yet to grok all the details, but already found some smaller issues.

Before I do a second, deeper, pass, I would like to ask you to cleanup the commits a bit, this would help me better understand the changes:
* Please merge "started x" and "finished x" type of commits.
* Avoid committing commented out code
* Avoid putting whitespace cleanups into more important commits.
* See my inline comments.

2022-04-27 12:41 UTC, lor11212 commented on PumaRhino/utils.h
> +	throw std::invalid_argument("Received type is not supported");
I tried several things with static_assert but couldn't make it work so far. I probably don't use it correctly. For this example, T should be an int or a double, so something like should work right?
```
template <typename T>
void fillMapBuilder(const std::wstring& /* key */, T /* value */, AttributeMapBuilderPtr& /* aBuilder */) {
	static_assert(std::is_same<T, int>::value || std::is_same<T, double>::value, "Type T should be either int or double");
}
```

2022-05-23 13:51 UTC, mistafunk requested changes
Looks good, just a few small issues left.
Quick functional check with the example scene looks good.

2022-05-23 13:51 UTC, mistafunk commented on PumaRhino/PumaGrasshopperAPI.cpp
> +#ifdef DEBUG
Consider introducing a `constexpr bool DBG` and use `if constexpr (DBG)` to query it.
The value of DBG can still be controlled through DEBUG compile definition if needed.

2022-05-23 13:51 UTC, mistafunk commented on PumaRhino/utils.cpp
> +}
template functions should be moved to the header file so they are fully visible to the compiler at their instantiation site.

2022-05-23 13:51 UTC, mistafunk commented on PumaRhino/utils.h
> +	throw std::invalid_argument("Received type is not supported");
I think you just forgot to allow bool as type as well:

```
static_assert(std::is_same<T, int>::value || std::is_same<T, double>::value || std::is_same<T, bool>::value,
	              "Type T must be one of int, double or bool");
```

2022-06-17 12:45 UTC, mistafunk approved these changes
LGTM, feel free to merge.

2022-06-17 12:59 UTC, merged