Single version source
Esri/puma pull request #49
Opened 2022-09-28 13:59 UTC by lor11212

JIRA: https://zrh-jira.esri.com/browse/CE-10315

This PR introduces a single source for the version of Puma in the file `version.properties`. The Rhino project, the Grasshopper project and the package creation script will all parse this file to get the version number.

**Implementation**

PumaRhino: Reads version.properties, parses each line to create `#define` macros, and write them to the `generatedVersion.h` file. This file is then used in version.h.

PumaGrasshopper: Reads and parses version.properties to create a version string and assign it to `AssemblyVersion` property.

Package creation: I added a function that reads and parses `version.properties`, and updates `manifest.yml` version line.

2022-09-30 08:09 UTC, chr11115 requested changes
Nice work! 
I'd suggest using template files with replacement tokens instead of "creating" the files from scratch through string manipulation.

2022-09-30 08:49 UTC, chr11115 commented on PumaRhino/PumaRhino.vcxproj
> +	<WriteLinesToFile File=".\generatedVersion.h" Lines="$(Version)" Overwrite="true"></WriteLinesToFile>
Update: 
It appears I linked a community version of msbuild. If msbuild does not offer similar functionality you can try to find an alternative way to fill a template file or leave it if it does not seem sensible.

2022-10-18 11:14 UTC, lor11212 commented
I incorporated your feedback 👍

2022-10-19 08:39 UTC, chr11115 requested changes
Good work! 
Found some minor formatting nags. 
Did a quick functional test and I noticed that a clean build is necessary to adapt any version changes made. 

I don't know the best approach to fix this, but adding the lines below to the targets in PumaGrasshopper.csproj/PumaRhino.vcxproj fixed the issue for me.
```
<PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
</PropertyGroup>
```
(https://stackoverflow.com/a/41803340)

2022-10-19 08:39 UTC, chr11115 commented on PumaRhino/PumaRhino.vcxproj
> +	<PropertyGroup>
Mixed tabs/spaces

2022-10-19 08:39 UTC, chr11115 commented on PumaGrasshopper/PumaGrasshopper.csproj
> +			  @(TemplateVersionStrings-&gt;
mixed tabs/spaces

2022-10-19 14:03 UTC, chr11115 approved these changes
LGTM, I decided to remove the hack to force build the version file. I guess it's better to require a force build every version change rather than forcing ms build tools over visual studio heuristics.. 
> A boolean value that applies to Visual Studio only. The Visual Studio build manager uses a process called FastUpToDateCheck to determine whether a project must be rebuilt to be up to date. This process is faster than using MSBuild to determine this. Setting the DisableFastUpToDateCheck property to true lets you bypass the Visual Studio build manager and force it to use MSBuild to determine whether the project is up to date.
(see https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022)

2022-10-19 14:52 UTC, merged